[WEKEA-BACKEND] 회원가입, 로그인 기능 구현
wecode-bootcamp-korea/30-1st-WEKEA-backend pull request #2
Opened 2022-03-03 11:54 UTC by Kimgwangil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 기능 구현
- 이메일, 비밀번호를 사용한 로그인 기능 구현
- 로그인 데코레이터 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 입력 데이터 정규표현식으로 작성 (백엔드)
- 이메일, 패스워드를 정규표현식으로 작성하여 형식에 맞지 않을 경우 에러 반환

2. 로그인 데이터 처리 (백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- 로그인 완료 시 로그인 토큰 발급

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 로그인 데코레이터는 개인적으로 조금 더 이해가 필요한 것 같습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-03-04 04:24 UTC, jamessoun93 requested changes

2022-03-04 04:24 UTC, jamessoun93 commented on users/utils.py
> +    return PASSWORD_REGEX
데코레이터 용도로 사용하는 함수가 아니라면 함수명은 명확한 의미 파악을 위해 동사로 시작해주시는게 좋습니다.
```suggestion
def validate_email(email):
    EMAIL_REGEX = re.match(r"^(\w+[+-_.]?\w?)+@([\w+-_.]+[.][\w+-_.]+)$", email)
    return EMAIL_REGEX

def validate_password(password):
    PASSWORD_REGEX = re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&?*])([a-zA-Z0-9!@#$%^&?*]){8,}$", password)
    return PASSWORD_REGEX
```

2022-03-04 04:24 UTC, jamessoun93 commented on users/utils.py
> +            request.user = user
```python
request.user = user
```
이 부분 어떤 의미인지 파악하고 계신지 확인을 위해 코멘트로 설명해주세요!

2022-03-04 04:24 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "INVALID_PASSWORD"})
- 반환해줄 http status code 추가해주세요.
- 여기서는 굳이 elif가 필요하지 않고 전부 if문으로 변경해주셔도 좋습니다. 
- 어짜피 특정조건이 truthy 하다면 무조건 return문을 만나기 때문에 elif 나 else는 불필요합니다.
```suggestion
            if not email_validation(email):
                return JsonResponse({"MESSAGE" : "INVALID_EMAIL"}, status=XXX)
                
            if not password_validation(password):
                return JsonResponse({"MESSAGE" : "INVALID_PASSWORD"}, status=XXX)
```

2022-03-04 04:24 UTC, jamessoun93 commented on users/views.py
> +            password        = data["password"]
프론트에서 보내주는 json body에 이 중 하나라도 존재하지 않을때 무슨일이 일어날까요?
파악되셨으면 에러처리 추가해주세요.

2022-03-04 04:24 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "ALREADY_EXIST_EMAIL"})
반환해줄 http status code 추가해주세요.

2022-03-04 05:20 UTC, Kimgwangil commented on users/views.py
> +            password        = data["password"]
프론트와 연결을 해보니 프론트에서 보내주는 값 중 json.body 가 비어있는 경우, `''` 빈 스트링으로 db에 저장이 됩니다.
빈 값으로 회원가입이 진행되면 안 되기 때문에, 프론트와 협의하여 프론트 측에서 입력된 값이 없는 경우 막아주기로 하였으나,
확실한 처리를 위해 에러처리를 추가하였습니다.

2022-03-04 05:56 UTC, Kimgwangil commented on users/utils.py
> +            request.user = user
처음 코드를 보며 억지로 이해하기로는 데코레이터의 영향을 받는 class의 user에  line 24에서 얻은 user_id 를 대입해준다고 생각했습니다.
하지만 천천히 읽어보다보니 해당 라인을 제거하여도 이상이 없겠다 판단했고, 실제로 제거하였을 때, 이상 없이 작동하는 것을 확인했습니다.

2022-03-04 05:56 UTC, Kimgwangil commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "INVALID_PASSWORD"})
수정하였습니다~

2022-03-04 05:56 UTC, Kimgwangil commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "ALREADY_EXIST_EMAIL"})
추가하였습니다~! 다음부턴 확인 잘 하겠습니다.

2022-03-04 05:57 UTC, Kimgwangil commented on users/utils.py
> +    return PASSWORD_REGEX
넵 수정하였습니다!

2022-03-04 07:15 UTC, jamessoun93 commented on users/utils.py
> +            request.user = user
정확히 말하면 request 객체에 user 라는 프로퍼티를 생성해서 해당 request 객체가 user 정보를 담아다주는 매개체 역할을 하는 것이죠. 이해가 좀 되실까요? 다들 이 부분 잘 이해못한 상태로 그냥 쓰는 경우가 많아서 짚고 넘어가야할 것 같았어요.

2022-03-04 07:20 UTC, Kimgwangil commented on users/utils.py
> +            request.user = user
넵 이해했습니다! 저도 이해하지 못한 상태에서 사용하다보니 항상 의문이었는데, 고민할 기회 주시고 알려주셔서 감사합니다!
이 부분은 따로 정리해놓겠습니다!

2022-03-04 07:28 UTC, jamessoun93 requested changes

2022-03-04 07:28 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_PASSWORD"}, status = 400)
유저 입력값에 대한 유효성 검사 조건은 기획에 따라 정말 많아질수도 있는 부분입니다. 조건이 새로 생길때마다 이렇게 if 문으로 나열한다면 if 문이 많아져 코드를 읽기 어렵게 됩니다. 이럴 때 `is_valid()` 라는 함수를 만들어 모든 validation 로직을 분리할 수 있고 해당 view 로직의 가독성을 높일 수 있습니다.

구체적으로 어떻게 함수를 분리할 수 해야할지는 직접 고민을 해보셨으면 좋겠으니 시도해보세요!

2022-03-04 07:28 UTC, jamessoun93 commented on users/views.py
> +
한줄이면 충분합니다.

2022-03-04 07:28 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status = 201)
- `201` 자체가 내포하고 있는 의미가 있으니 프론트의 요청이 없는 한 굳이 JSON Body를 포함시킬 필요가 없습니다.
- JsonResponse() 대신 HttpResponse()를 사용해 status code 만 반환해줄 수 있습니다.

2022-03-04 07:28 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS", "ACCESS_TOKEN" : access_token}, status = 201)
- message 없이 access_token만 있으면 충분하고 소문자로 통일해주세요.
- 로그인인데 status code가 201이 알맞을까요?

2022-03-07 00:26 UTC, Kimgwangil commented on users/views.py
> +
넵 반영했습니다 !

2022-03-07 00:35 UTC, Kimgwangil commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_PASSWORD"}, status = 400)
유효성을 검사하는 함수를 따로 분리하는 과정에서 인자를 어떤 것을 받아야하는지 data, request, *args ... 이것저것 넣어보고 시도해본 결과 다른 것은 에러가 발생하고, `data`, 혹은 회원가입에 필요한 모든 인자(full_name, email~gender_id)를 넣었을 때 정상 작동하는 것으로 확인하였습니다.
is_valid() 함수를 분리하여 발생할 수 있는 모든 validation 로직을 관리하니 가독성도 좋아지고, 훨씬 깔끔해진 것 같습니다.

2022-03-07 00:37 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS"}, status = 201)
아! 넵 반영했습니다 !
회원가입 외에도 새로운 데이터가 생성되는 경우에는 프론트의 요청이 없는 한 JSON Body를 포함시킬 필요 없이 status code만 반환해주면 되는 부분일까요??

2022-03-07 00:45 UTC, Kimgwangil commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS", "ACCESS_TOKEN" : access_token}, status = 201)
http 상태 코드에 대해 다시 보고 왔습니다.
로그인 기능은  `HEAD: 개체 해더가 메시지 바디에 있다.` 이 부분에 해당되는 것으로 판단하여 status code = 200  을 반환하였습니다.

2022-03-08 03:10 UTC, jamessoun93 approved these changes

2022-03-08 03:11 UTC, merged